version: '3.9'

services:
  dev-empleados-db:
    container_name: dev-empleados-db
    image: postgres:13
    restart: "no"
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: empleados
      POSTGRES_USER: empleados
      POSTGRES_PASSWORD: empleados
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  dev-empleados-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dev-empleados-backend
    container_name: dev-empleados-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - dev-empleados-db
    environment:
      - DATABASE_URL=postgres://empleados:empleados@db:5432/empleados
    networks:
      - backend-network

  dev-empleados-frontend:
    container_name: dev-empleados-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "9000:9000"
    restart: "no"
    depends_on:
      - dev-empleados-backend

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
