# Generated by Django 5.0.6 on 2024-08-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_person_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bussines',
            new_name='business',
        ),
    ]
