# Generated by Django 5.0.6 on 2024-08-21 00:01

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name="Administrador")
    Group.objects.create(name="Usuario")


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_uuid'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
