# Generated by Django 5.0.6 on 2024-08-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION count_people_inside_today()
            RETURNS INTEGER AS $$
            DECLARE
                people_inside_count INTEGER;
            BEGIN
                SELECT COUNT(*)
                INTO people_inside_count
                FROM checking_check
                WHERE check_in::date = CURRENT_DATE
                  AND check_out IS NULL;

                RETURN people_inside_count;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            DROP FUNCTION IF EXISTS count_people_inside_today();
            """
        ),
    ]
