# Generated by Django 5.0.6 on 2024-08-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0005_get_checking_reports_range'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION get_checking_reports_area_range(
                area_id_param INTEGER,
                start_date TIMESTAMPTZ,
                end_date TIMESTAMPTZ
            )
            RETURNS TABLE(
                uuid UUID,
                person_id BIGINT,
                person_name VARCHAR,
                person_document VARCHAR,
                check_in TIMESTAMPTZ,
                check_out TIMESTAMPTZ,
                reason INTEGER,
                created TIMESTAMPTZ,
                modified TIMESTAMPTZ
            ) AS $$
            BEGIN
                RETURN QUERY
                SELECT 
                    chk.uuid,
                    chk.person_id,
                    rp.name AS person_name,
                    rp.document AS person_document,
                    chk.check_in,
                    chk.check_out,
                    chk.reason,
                    chk.created,
                    chk.modified
                FROM register_area ra
                JOIN register_person rp ON rp.area_id = ra.id
                JOIN checking_check chk ON chk.person_id = rp.id
                WHERE 
                    ra.id = area_id_param
                    AND chk.check_in >= start_date
                    AND chk.check_out <= end_date;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            DROP FUNCTION IF EXISTS get_checking_reports_area_range();
            """
        ),
    ]
